import Link from "next/link";
import { ArrowLeft } from "lucide-react";
import { Button } from "@/components/ui/button";

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-canvas text-ink py-24 px-6">
      <div className="mx-auto max-w-3xl">
        <Button variant="ghost" asChild className="mb-8 -ml-4">
          <Link href="/">
            <ArrowLeft className="mr-2 h-4 w-4" />
            Back to Home
          </Link>
        </Button>
        <h1 className="font-serif text-4xl md:text-5xl mb-8">Terms and Conditions</h1>
        
        <div className="prose prose-neutral max-w-none space-y-6 text-ink-muted">
          <p>Last updated: {new Date().toLocaleDateString()}</p>
          
          <h2 className="font-serif text-2xl text-ink">1. Agreement to Terms</h2>
          <p>
            By accessing or using Voxa, you agree to be bound by these Terms and Conditions. 
            If you disagree with any part of the terms, then you may not access the service.
          </p>

          <h2 className="font-serif text-2xl text-ink">2. Description of Service</h2>
          <p>
            Voxa is an AI-powered communication coaching platform. We provide simulated practice 
            scenarios and feedback generated by artificial intelligence. The feedback provided is 
            for educational and improvement purposes only.
          </p>

          <h2 className="font-serif text-2xl text-ink">3. User Accounts</h2>
          <p>
            When you create an account with us, you must provide information that is accurate, 
            complete, and current at all times. Failure to do so constitutes a breach of the Terms, 
            which may result in immediate termination of your account on our Service.
          </p>

          <h2 className="font-serif text-2xl text-ink">4. Intellectual Property</h2>
          <p>
            The Service and its original content, features, and functionality are and will remain 
            the exclusive property of Voxa and its licensors.
          </p>

          <h2 className="font-serif text-2xl text-ink">5. Changes</h2>
          <p>
            We reserve the right, at our sole discretion, to modify or replace these Terms at any time. 
            By continuing to access or use our Service after those revisions become effective, you agree 
            to be bound by the revised terms.
          </p>
        </div>
      </div>
    </div>
  );
}
